### ISSUE TITLE
Dependency version of java

### ISSUE THREAD

**Issue by xumingming** [oembedler/spring-graphql-common#5]
Just out of curiosity, why `spring-graphql-common` depends on java `1.8`, rather than some lower version like  `1.6`? our production system is using jdk `1.6` now, but we want to use this lib.

**Comment by damnhandy** [comment]
-1 

For something like GraphQL, I can't imagine not being to take advantage of Java8 language features. Given that both Java 6 and 7 are both no longer supported by Oracle, it doesn't seem like a positive move forward. Not to mention that SpringBoot only supports Java 7 as a minimum. Please keep Java 8.
